CREATE DATABASE IF NOT EXISTS SPRING_TEST CHARACTER SET utf8;

use SPRING_TEST;

-- テーブルの削除
--DROP TABLE CO_M_GENGOU_INFO;

CREATE TABLE IF NOT EXISTS CO_M_GENGOU_INFO
(
    CODE               CHAR(2)       NOT NULL PRIMARY KEY,
    GENGOU             CHAR(10)      NOT NULL,
    START_DATE         CHAR(8)       NOT NULL,
    END_DATE           CHAR(8)       NOT NULL,
    INS_USER_ID        VARCHAR(20)   NOT NULL,
    INS_DATE           TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UPD_USER_ID        VARCHAR(20)   ,
    UPD_DATE           TIMESTAMP(3)  DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), /* 更新タイムスタンプ自動設定 */
    UPD_FUNC_ID        CHAR(12) NOT NULL
) ENGINE=InnoDB;

ALTER TABLE CO_M_GENGOU_INFO ADD INDEX CO_M_GENGOU_INFO_IDX1(CODE);
ALTER TABLE CO_M_GENGOU_INFO ADD INDEX CO_M_GENGOU_INFO_IDX2(START_DATE);
ALTER TABLE CO_M_GENGOU_INFO ADD INDEX CO_M_GENGOU_INFO_IDX3(END_DATE);

INSERT INTO CO_M_GENGOU_INFO(CODE, GENGOU, START_DATE, END_DATE, INS_USER_ID, UPD_FUNC_ID) VALUES ('01', '明治', '18680125', '19120729', 'SYSTEM', 'SYSTEM');
INSERT INTO CO_M_GENGOU_INFO(CODE, GENGOU, START_DATE, END_DATE, INS_USER_ID, UPD_FUNC_ID) VALUES ('02', '大正', '19120730', '19261224', 'SYSTEM', 'SYSTEM');
INSERT INTO CO_M_GENGOU_INFO(CODE, GENGOU, START_DATE, END_DATE, INS_USER_ID, UPD_FUNC_ID) VALUES ('03', '昭和', '19261225', '19890107', 'SYSTEM', 'SYSTEM');
INSERT INTO CO_M_GENGOU_INFO(CODE, GENGOU, START_DATE, END_DATE, INS_USER_ID, UPD_FUNC_ID) VALUES ('04', '平成', '19890108', '99999999', 'SYSTEM', 'SYSTEM');
