package jp.co.fukuya_k.db.generator;

import java.math.BigDecimal;
import java.util.Date;
import jp.co.fukuya_k.system.interfaces.FukuyaEntityInterface;

public class Emp implements FukuyaEntityInterface {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column KENSYU.EMP.EMPNO
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	private String empno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column KENSYU.EMP.ENAME
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	private String ename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column KENSYU.EMP.JOB
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	private String job;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column KENSYU.EMP.MGR
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	private String mgr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column KENSYU.EMP.HIREDATE
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	private Date hiredate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column KENSYU.EMP.SAL
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	private BigDecimal sal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column KENSYU.EMP.COMM
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	private BigDecimal comm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column KENSYU.EMP.DEPTNO
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	private Short deptno;
	
	private String dname;
	
	private String loc;

	public String getLoc() {
		return loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

	public String getDname() {
		return dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column KENSYU.EMP.EMPNO
	 * @return  the value of KENSYU.EMP.EMPNO
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public String getEmpno() {
		return empno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column KENSYU.EMP.EMPNO
	 * @param empno  the value for KENSYU.EMP.EMPNO
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public void setEmpno(String empno) {
		this.empno = empno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column KENSYU.EMP.ENAME
	 * @return  the value of KENSYU.EMP.ENAME
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public String getEname() {
		return ename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column KENSYU.EMP.ENAME
	 * @param ename  the value for KENSYU.EMP.ENAME
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public void setEname(String ename) {
		this.ename = ename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column KENSYU.EMP.JOB
	 * @return  the value of KENSYU.EMP.JOB
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public String getJob() {
		return job;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column KENSYU.EMP.JOB
	 * @param job  the value for KENSYU.EMP.JOB
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public void setJob(String job) {
		this.job = job;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column KENSYU.EMP.MGR
	 * @return  the value of KENSYU.EMP.MGR
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public String getMgr() {
		return mgr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column KENSYU.EMP.MGR
	 * @param mgr  the value for KENSYU.EMP.MGR
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public void setMgr(String mgr) {
		this.mgr = mgr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column KENSYU.EMP.HIREDATE
	 * @return  the value of KENSYU.EMP.HIREDATE
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public Date getHiredate() {
		return hiredate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column KENSYU.EMP.HIREDATE
	 * @param hiredate  the value for KENSYU.EMP.HIREDATE
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public void setHiredate(Date hiredate) {
		this.hiredate = hiredate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column KENSYU.EMP.SAL
	 * @return  the value of KENSYU.EMP.SAL
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public BigDecimal getSal() {
		return sal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column KENSYU.EMP.SAL
	 * @param sal  the value for KENSYU.EMP.SAL
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public void setSal(BigDecimal sal) {
		this.sal = sal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column KENSYU.EMP.COMM
	 * @return  the value of KENSYU.EMP.COMM
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public BigDecimal getComm() {
		return comm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column KENSYU.EMP.COMM
	 * @param comm  the value for KENSYU.EMP.COMM
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public void setComm(BigDecimal comm) {
		this.comm = comm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column KENSYU.EMP.DEPTNO
	 * @return  the value of KENSYU.EMP.DEPTNO
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public Short getDeptno() {
		return deptno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column KENSYU.EMP.DEPTNO
	 * @param deptno  the value for KENSYU.EMP.DEPTNO
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public void setDeptno(Short deptno) {
		this.deptno = deptno;
	}

	// ADD START FW都合 研修には影響なし
	private String insUserId;
	private Date insDate;
	private String updUserId;
	private Date updDate;
	private String updFuncId;
    
	public String getInsUserId() {
		return insUserId;
	}

	public void setInsUserId(String insUserId) {
		this.insUserId = insUserId;
	}

	public Date getInsDate() {
		return insDate;
	}

	public void setInsDate(Date insDate) {
		this.insDate = insDate;
	}

	public String getUpdUserId() {
		return updUserId;
	}

	public void setUpdUserId(String updUserId) {
		this.updUserId = updUserId;
	}

	public Date getUpdDate() {
		return updDate;
	}

	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}

	public String getUpdFuncId() {
		return updFuncId;
	}

	public void setUpdFuncId(String updFuncId) {
		this.updFuncId = updFuncId;
	}
	// ADD END FW都合 研修には影響なし
}