package jp.co.fukuya_k.db.generator;

import java.util.List;
import jp.co.fukuya_k.db.generator.Emp;
import jp.co.fukuya_k.db.generator.EmpHelper;
import org.apache.ibatis.annotations.Param;

public interface EmpMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.EMP
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int countByHelper(EmpHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.EMP
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int deleteByHelper(EmpHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.EMP
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int deleteByPrimaryKey(String empno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.EMP
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int insert(Emp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.EMP
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int insertSelective(Emp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.EMP
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	List<Emp> selectByHelper(EmpHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.EMP
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	Emp selectByPrimaryKey(String empno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.EMP
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int updateByHelperSelective(@Param("record") Emp record, @Param("example") EmpHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.EMP
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int updateByHelper(@Param("record") Emp record, @Param("example") EmpHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.EMP
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int updateByPrimaryKeySelective(Emp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.EMP
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int updateByPrimaryKey(Emp record);
}