package jp.co.fukuya_k.db.generator;

import java.util.List;
import jp.co.fukuya_k.db.generator.Fresh;
import jp.co.fukuya_k.db.generator.FreshHelper;
import org.apache.ibatis.annotations.Param;

public interface FreshMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.FRESH
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int countByHelper(FreshHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.FRESH
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int deleteByHelper(FreshHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.FRESH
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int deleteByPrimaryKey(String empno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.FRESH
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int insert(Fresh record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.FRESH
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int insertSelective(Fresh record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.FRESH
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	List<Fresh> selectByHelper(FreshHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.FRESH
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	Fresh selectByPrimaryKey(String empno);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.FRESH
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int updateByHelperSelective(@Param("record") Fresh record, @Param("example") FreshHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.FRESH
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int updateByHelper(@Param("record") Fresh record, @Param("example") FreshHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.FRESH
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int updateByPrimaryKeySelective(Fresh record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.FRESH
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int updateByPrimaryKey(Fresh record);
}