package jp.co.fukuya_k.db.generator;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import jp.co.fukuya_k.db.generator.MAuthDetail;
import jp.co.fukuya_k.db.generator.MAuthDetailHelper;
import jp.co.fukuya_k.db.generator.MAuthDetailKey;

public interface MAuthDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_DETAIL
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int countByHelper(MAuthDetailHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_DETAIL
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int deleteByHelper(MAuthDetailHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_DETAIL
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int deleteByPrimaryKey(MAuthDetailKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_DETAIL
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int insert(MAuthDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_DETAIL
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int insertSelective(MAuthDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_DETAIL
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	List<MAuthDetail> selectByHelper(MAuthDetailHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_DETAIL
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	MAuthDetail selectByPrimaryKey(MAuthDetailKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_DETAIL
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int updateByHelperSelective(@Param("record") MAuthDetail record, @Param("example") MAuthDetailHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_DETAIL
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int updateByHelper(@Param("record") MAuthDetail record, @Param("example") MAuthDetailHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_DETAIL
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int updateByPrimaryKeySelective(MAuthDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_DETAIL
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int updateByPrimaryKey(MAuthDetail record);
}