package jp.co.fukuya_k.db.generator;

import java.util.Date;

import jp.co.fukuya_k.system.interfaces.FukuyaEntityInterface;

public class MAuthUser implements FukuyaEntityInterface {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column KENSYU.M_AUTH_USER.USER_ID
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column KENSYU.M_AUTH_USER.PASSWORD
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column KENSYU.M_AUTH_USER.AUTH_CD
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	private String authCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column KENSYU.M_AUTH_USER.UPD_FUNC_ID
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	private String updFuncId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column KENSYU.M_AUTH_USER.INS_USER_ID
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	private String insUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column KENSYU.M_AUTH_USER.INS_DATE
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	private Date insDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column KENSYU.M_AUTH_USER.UPD_USER_ID
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	private String updUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column KENSYU.M_AUTH_USER.UPD_DATE
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	private Date updDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column KENSYU.M_AUTH_USER.USER_ID
	 * @return  the value of KENSYU.M_AUTH_USER.USER_ID
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column KENSYU.M_AUTH_USER.USER_ID
	 * @param userId  the value for KENSYU.M_AUTH_USER.USER_ID
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column KENSYU.M_AUTH_USER.PASSWORD
	 * @return  the value of KENSYU.M_AUTH_USER.PASSWORD
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column KENSYU.M_AUTH_USER.PASSWORD
	 * @param password  the value for KENSYU.M_AUTH_USER.PASSWORD
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column KENSYU.M_AUTH_USER.AUTH_CD
	 * @return  the value of KENSYU.M_AUTH_USER.AUTH_CD
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public String getAuthCd() {
		return authCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column KENSYU.M_AUTH_USER.AUTH_CD
	 * @param authCd  the value for KENSYU.M_AUTH_USER.AUTH_CD
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public void setAuthCd(String authCd) {
		this.authCd = authCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column KENSYU.M_AUTH_USER.UPD_FUNC_ID
	 * @return  the value of KENSYU.M_AUTH_USER.UPD_FUNC_ID
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public String getUpdFuncId() {
		return updFuncId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column KENSYU.M_AUTH_USER.UPD_FUNC_ID
	 * @param updFuncId  the value for KENSYU.M_AUTH_USER.UPD_FUNC_ID
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public void setUpdFuncId(String updFuncId) {
		this.updFuncId = updFuncId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column KENSYU.M_AUTH_USER.INS_USER_ID
	 * @return  the value of KENSYU.M_AUTH_USER.INS_USER_ID
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public String getInsUserId() {
		return insUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column KENSYU.M_AUTH_USER.INS_USER_ID
	 * @param insUserId  the value for KENSYU.M_AUTH_USER.INS_USER_ID
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public void setInsUserId(String insUserId) {
		this.insUserId = insUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column KENSYU.M_AUTH_USER.INS_DATE
	 * @return  the value of KENSYU.M_AUTH_USER.INS_DATE
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public Date getInsDate() {
		return insDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column KENSYU.M_AUTH_USER.INS_DATE
	 * @param insDate  the value for KENSYU.M_AUTH_USER.INS_DATE
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public void setInsDate(Date insDate) {
		this.insDate = insDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column KENSYU.M_AUTH_USER.UPD_USER_ID
	 * @return  the value of KENSYU.M_AUTH_USER.UPD_USER_ID
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public String getUpdUserId() {
		return updUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column KENSYU.M_AUTH_USER.UPD_USER_ID
	 * @param updUserId  the value for KENSYU.M_AUTH_USER.UPD_USER_ID
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public void setUpdUserId(String updUserId) {
		this.updUserId = updUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column KENSYU.M_AUTH_USER.UPD_DATE
	 * @return  the value of KENSYU.M_AUTH_USER.UPD_DATE
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public Date getUpdDate() {
		return updDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column KENSYU.M_AUTH_USER.UPD_DATE
	 * @param updDate  the value for KENSYU.M_AUTH_USER.UPD_DATE
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public void setUpdDate(Date updDate) {
		this.updDate = updDate;
	}
}