package jp.co.fukuya_k.db.generator;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import jp.co.fukuya_k.db.generator.MAuthUser;
import jp.co.fukuya_k.db.generator.MAuthUserHelper;

public interface MAuthUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_USER
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int countByHelper(MAuthUserHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_USER
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int deleteByHelper(MAuthUserHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_USER
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_USER
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int insert(MAuthUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_USER
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int insertSelective(MAuthUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_USER
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	List<MAuthUser> selectByHelper(MAuthUserHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_USER
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	MAuthUser selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_USER
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int updateByHelperSelective(@Param("record") MAuthUser record, @Param("example") MAuthUserHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_USER
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int updateByHelper(@Param("record") MAuthUser record, @Param("example") MAuthUserHelper example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_USER
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int updateByPrimaryKeySelective(MAuthUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table KENSYU.M_AUTH_USER
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	int updateByPrimaryKey(MAuthUser record);
}