package jp.co.fukuya_k.db.generator;

public class MAuthDetailKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column KENSYU.M_AUTH_DETAIL.SEQ
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	private Long seq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column KENSYU.M_AUTH_DETAIL.AUTH_CD
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	private String authCd;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column KENSYU.M_AUTH_DETAIL.SEQ
	 * @return  the value of KENSYU.M_AUTH_DETAIL.SEQ
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public Long getSeq() {
		return seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column KENSYU.M_AUTH_DETAIL.SEQ
	 * @param seq  the value for KENSYU.M_AUTH_DETAIL.SEQ
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public void setSeq(Long seq) {
		this.seq = seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column KENSYU.M_AUTH_DETAIL.AUTH_CD
	 * @return  the value of KENSYU.M_AUTH_DETAIL.AUTH_CD
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public String getAuthCd() {
		return authCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column KENSYU.M_AUTH_DETAIL.AUTH_CD
	 * @param authCd  the value for KENSYU.M_AUTH_DETAIL.AUTH_CD
	 * @mbggenerated  Wed Jun 08 18:01:06 JST 2016
	 */
	public void setAuthCd(String authCd) {
		this.authCd = authCd;
	}
}